Config = {}

Config.animation = true

Config.particul = true


---en peux metre un skin sur tous ses arme (ajoute des arme si tu veux)
Config.weaponTintList = {
    "WEAPON_PISTOL",
    "WEAPON_PISTOL50",
    "WEAPON_APPISTOL",
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_MICROSMG",
    "WEAPON_SMG",
    "WEAPON_RPG",
    "WEAPON_MARKSMANRIFLE_MK2",
    "WEAPON_MARKSMANRIFLE",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_HEAVYSNIPER",
    "WEAPON_SNIPERRIFLE",
    "WEAPON_GUSENBERG",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_COMBATMG",
    "WEAPON_MG",
    "WEAPON_COMPACTRIFLE",
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_SPECIALCARBINE_MK2",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_CARBINERIFLE",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_AUTOSHOTGUN",
    "WEAPON_DBSHOTGUN",
    "WEAPON_HEAVYSHOTGUN",
    
}